// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Edge struct {
	Node *Node `json:"node"`
	From *Node `json:"from"`
	To   *Node `json:"to"`
}

type EdgeConnection struct {
	Cursor     string    `json:"cursor"`
	TotalCount int       `json:"totalCount"`
	Edge       []*Edge   `json:"edge"`
	PageInfo   *PageInfo `json:"pageInfo"`
}

type EdgeInput struct {
	Node *NodeInput  `json:"node"`
	From *ForeignKey `json:"from"`
	To   *ForeignKey `json:"to"`
}

type Filter struct {
	Key      string      `json:"key"`
	Operator string      `json:"operator"`
	Value    interface{} `json:"value"`
}

type ForeignKey struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

type Node struct {
	ID         string                 `json:"id"`
	Type       string                 `json:"type"`
	Attributes map[string]interface{} `json:"attributes"`
	Edges      *EdgeConnection        `json:"edges"`
}

type NodeInput struct {
	ID         *string                `json:"id"`
	Type       string                 `json:"type"`
	Attributes map[string]interface{} `json:"attributes"`
}

type PageInfo struct {
	StartCursor string `json:"startCursor"`
	EndCursor   string `json:"endCursor"`
	HasNextPage bool   `json:"hasNextPage"`
}

type QueryEdges struct {
	Type    string    `json:"type"`
	Filters []*Filter `json:"filters"`
	Limit   int       `json:"limit"`
}

type QueryNodes struct {
	Type    string    `json:"type"`
	Filters []*Filter `json:"filters"`
	Limit   int       `json:"limit"`
}
