// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/graphik.proto

package apipb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Op int32

const (
	Op_CREATE_NODE Op = 0
	Op_PATCH_NODE  Op = 1
	Op_DELETE_NODE Op = 2
	Op_CREATE_EDGE Op = 3
	Op_PATCH_EDGE  Op = 4
	Op_DELETE_EDGE Op = 5
)

var Op_name = map[int32]string{
	0: "CREATE_NODE",
	1: "PATCH_NODE",
	2: "DELETE_NODE",
	3: "CREATE_EDGE",
	4: "PATCH_EDGE",
	5: "DELETE_EDGE",
}

var Op_value = map[string]int32{
	"CREATE_NODE": 0,
	"PATCH_NODE":  1,
	"DELETE_NODE": 2,
	"CREATE_EDGE": 3,
	"PATCH_EDGE":  4,
	"DELETE_EDGE": 5,
}

func (x Op) String() string {
	return proto.EnumName(Op_name, int32(x))
}

func (Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{0}
}

type Keyword int32

const (
	Keyword_ANY     Keyword = 0
	Keyword_DEFAULT Keyword = 1
)

var Keyword_name = map[int32]string{
	0: "ANY",
	1: "DEFAULT",
}

var Keyword_value = map[string]int32{
	"ANY":     0,
	"DEFAULT": 1,
}

func (x Keyword) String() string {
	return proto.EnumName(Keyword_name, int32(x))
}

func (Keyword) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{1}
}

type Command struct {
	Op                   Op                   `protobuf:"varint,1,opt,name=op,proto3,enum=api.Op" json:"op,omitempty"`
	Val                  *any.Any             `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetOp() Op {
	if m != nil {
		return m.Op
	}
	return Op_CREATE_NODE
}

func (m *Command) GetVal() *any.Any {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *Command) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Counter struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Counter) Reset()         { *m = Counter{} }
func (m *Counter) String() string { return proto.CompactTextString(m) }
func (*Counter) ProtoMessage()    {}
func (*Counter) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{1}
}

func (m *Counter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Counter.Unmarshal(m, b)
}
func (m *Counter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Counter.Marshal(b, m, deterministic)
}
func (m *Counter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Counter.Merge(m, src)
}
func (m *Counter) XXX_Size() int {
	return xxx_messageInfo_Counter.Size(m)
}
func (m *Counter) XXX_DiscardUnknown() {
	xxx_messageInfo_Counter.DiscardUnknown(m)
}

var xxx_messageInfo_Counter proto.InternalMessageInfo

func (m *Counter) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Path struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{2}
}

func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (m *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(m, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Path) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Node struct {
	Path                 *Path                `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Attributes           *_struct.Struct      `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{3}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *Node) GetAttributes() *_struct.Struct {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Node) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Node) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type Message struct {
	Channel              string          `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Type                 string          `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Attributes           *_struct.Struct `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{4}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Message) GetAttributes() *_struct.Struct {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type Filter struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Expressions          []string `protobuf:"bytes,2,rep,name=expressions,proto3" json:"expressions,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{5}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Filter) GetExpressions() []string {
	if m != nil {
		return m.Expressions
	}
	return nil
}

func (m *Filter) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Export struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges                []*Edge  `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Export) Reset()         { *m = Export{} }
func (m *Export) String() string { return proto.CompactTextString(m) }
func (*Export) ProtoMessage()    {}
func (*Export) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{6}
}

func (m *Export) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Export.Unmarshal(m, b)
}
func (m *Export) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Export.Marshal(b, m, deterministic)
}
func (m *Export) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Export.Merge(m, src)
}
func (m *Export) XXX_Size() int {
	return xxx_messageInfo_Export.Size(m)
}
func (m *Export) XXX_DiscardUnknown() {
	xxx_messageInfo_Export.DiscardUnknown(m)
}

var xxx_messageInfo_Export proto.InternalMessageInfo

func (m *Export) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Export) GetEdges() []*Edge {
	if m != nil {
		return m.Edges
	}
	return nil
}

type Patch struct {
	Path                 *Path           `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Patch                *_struct.Struct `protobuf:"bytes,2,opt,name=patch,proto3" json:"patch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Patch) Reset()         { *m = Patch{} }
func (m *Patch) String() string { return proto.CompactTextString(m) }
func (*Patch) ProtoMessage()    {}
func (*Patch) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{7}
}

func (m *Patch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Patch.Unmarshal(m, b)
}
func (m *Patch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Patch.Marshal(b, m, deterministic)
}
func (m *Patch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Patch.Merge(m, src)
}
func (m *Patch) XXX_Size() int {
	return xxx_messageInfo_Patch.Size(m)
}
func (m *Patch) XXX_DiscardUnknown() {
	xxx_messageInfo_Patch.DiscardUnknown(m)
}

var xxx_messageInfo_Patch proto.InternalMessageInfo

func (m *Patch) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *Patch) GetPatch() *_struct.Struct {
	if m != nil {
		return m.Patch
	}
	return nil
}

type Edge struct {
	Path                 *Path                `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mutual               bool                 `protobuf:"varint,2,opt,name=mutual,proto3" json:"mutual,omitempty"`
	Attributes           *_struct.Struct      `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	From                 *Path                `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Path                `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Edge) Reset()         { *m = Edge{} }
func (m *Edge) String() string { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()    {}
func (*Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{8}
}

func (m *Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Edge.Unmarshal(m, b)
}
func (m *Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Edge.Marshal(b, m, deterministic)
}
func (m *Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Edge.Merge(m, src)
}
func (m *Edge) XXX_Size() int {
	return xxx_messageInfo_Edge.Size(m)
}
func (m *Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Edge proto.InternalMessageInfo

func (m *Edge) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *Edge) GetMutual() bool {
	if m != nil {
		return m.Mutual
	}
	return false
}

func (m *Edge) GetAttributes() *_struct.Struct {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Edge) GetFrom() *Path {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Edge) GetTo() *Path {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Edge) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Edge) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type EdgeFilters struct {
	EdgesFrom            []*Filter `protobuf:"bytes,1,rep,name=edges_from,json=edgesFrom,proto3" json:"edges_from,omitempty"`
	EdgesTo              []*Filter `protobuf:"bytes,2,rep,name=edges_to,json=edgesTo,proto3" json:"edges_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EdgeFilters) Reset()         { *m = EdgeFilters{} }
func (m *EdgeFilters) String() string { return proto.CompactTextString(m) }
func (*EdgeFilters) ProtoMessage()    {}
func (*EdgeFilters) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{9}
}

func (m *EdgeFilters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeFilters.Unmarshal(m, b)
}
func (m *EdgeFilters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeFilters.Marshal(b, m, deterministic)
}
func (m *EdgeFilters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeFilters.Merge(m, src)
}
func (m *EdgeFilters) XXX_Size() int {
	return xxx_messageInfo_EdgeFilters.Size(m)
}
func (m *EdgeFilters) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeFilters.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeFilters proto.InternalMessageInfo

func (m *EdgeFilters) GetEdgesFrom() []*Filter {
	if m != nil {
		return m.EdgesFrom
	}
	return nil
}

func (m *EdgeFilters) GetEdgesTo() []*Filter {
	if m != nil {
		return m.EdgesTo
	}
	return nil
}

type RaftJoinRequest struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftJoinRequest) Reset()         { *m = RaftJoinRequest{} }
func (m *RaftJoinRequest) String() string { return proto.CompactTextString(m) }
func (*RaftJoinRequest) ProtoMessage()    {}
func (*RaftJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{10}
}

func (m *RaftJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftJoinRequest.Unmarshal(m, b)
}
func (m *RaftJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftJoinRequest.Marshal(b, m, deterministic)
}
func (m *RaftJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftJoinRequest.Merge(m, src)
}
func (m *RaftJoinRequest) XXX_Size() int {
	return xxx_messageInfo_RaftJoinRequest.Size(m)
}
func (m *RaftJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RaftJoinRequest proto.InternalMessageInfo

func (m *RaftJoinRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *RaftJoinRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type RaftJoinResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftJoinResponse) Reset()         { *m = RaftJoinResponse{} }
func (m *RaftJoinResponse) String() string { return proto.CompactTextString(m) }
func (*RaftJoinResponse) ProtoMessage()    {}
func (*RaftJoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{11}
}

func (m *RaftJoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftJoinResponse.Unmarshal(m, b)
}
func (m *RaftJoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftJoinResponse.Marshal(b, m, deterministic)
}
func (m *RaftJoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftJoinResponse.Merge(m, src)
}
func (m *RaftJoinResponse) XXX_Size() int {
	return xxx_messageInfo_RaftJoinResponse.Size(m)
}
func (m *RaftJoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftJoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RaftJoinResponse proto.InternalMessageInfo

type GetJWKSRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJWKSRequest) Reset()         { *m = GetJWKSRequest{} }
func (m *GetJWKSRequest) String() string { return proto.CompactTextString(m) }
func (*GetJWKSRequest) ProtoMessage()    {}
func (*GetJWKSRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{12}
}

func (m *GetJWKSRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJWKSRequest.Unmarshal(m, b)
}
func (m *GetJWKSRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJWKSRequest.Marshal(b, m, deterministic)
}
func (m *GetJWKSRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJWKSRequest.Merge(m, src)
}
func (m *GetJWKSRequest) XXX_Size() int {
	return xxx_messageInfo_GetJWKSRequest.Size(m)
}
func (m *GetJWKSRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJWKSRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJWKSRequest proto.InternalMessageInfo

type GetJWKSResponse struct {
	Jwks                 map[string]string `protobuf:"bytes,1,rep,name=jwks,proto3" json:"jwks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetJWKSResponse) Reset()         { *m = GetJWKSResponse{} }
func (m *GetJWKSResponse) String() string { return proto.CompactTextString(m) }
func (*GetJWKSResponse) ProtoMessage()    {}
func (*GetJWKSResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{13}
}

func (m *GetJWKSResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJWKSResponse.Unmarshal(m, b)
}
func (m *GetJWKSResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJWKSResponse.Marshal(b, m, deterministic)
}
func (m *GetJWKSResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJWKSResponse.Merge(m, src)
}
func (m *GetJWKSResponse) XXX_Size() int {
	return xxx_messageInfo_GetJWKSResponse.Size(m)
}
func (m *GetJWKSResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJWKSResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJWKSResponse proto.InternalMessageInfo

func (m *GetJWKSResponse) GetJwks() map[string]string {
	if m != nil {
		return m.Jwks
	}
	return nil
}

type UpdateJWKSRequest struct {
	Jwks                 map[string]string `protobuf:"bytes,1,rep,name=jwks,proto3" json:"jwks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateJWKSRequest) Reset()         { *m = UpdateJWKSRequest{} }
func (m *UpdateJWKSRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateJWKSRequest) ProtoMessage()    {}
func (*UpdateJWKSRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{14}
}

func (m *UpdateJWKSRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJWKSRequest.Unmarshal(m, b)
}
func (m *UpdateJWKSRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJWKSRequest.Marshal(b, m, deterministic)
}
func (m *UpdateJWKSRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJWKSRequest.Merge(m, src)
}
func (m *UpdateJWKSRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateJWKSRequest.Size(m)
}
func (m *UpdateJWKSRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJWKSRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJWKSRequest proto.InternalMessageInfo

func (m *UpdateJWKSRequest) GetJwks() map[string]string {
	if m != nil {
		return m.Jwks
	}
	return nil
}

type UpdateJWKSResponse struct {
	Jwks                 map[string]string `protobuf:"bytes,1,rep,name=jwks,proto3" json:"jwks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateJWKSResponse) Reset()         { *m = UpdateJWKSResponse{} }
func (m *UpdateJWKSResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateJWKSResponse) ProtoMessage()    {}
func (*UpdateJWKSResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{15}
}

func (m *UpdateJWKSResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJWKSResponse.Unmarshal(m, b)
}
func (m *UpdateJWKSResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJWKSResponse.Marshal(b, m, deterministic)
}
func (m *UpdateJWKSResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJWKSResponse.Merge(m, src)
}
func (m *UpdateJWKSResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateJWKSResponse.Size(m)
}
func (m *UpdateJWKSResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJWKSResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJWKSResponse proto.InternalMessageInfo

func (m *UpdateJWKSResponse) GetJwks() map[string]string {
	if m != nil {
		return m.Jwks
	}
	return nil
}

type SearchNodesRequest struct {
	Filter               *Filter  `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchNodesRequest) Reset()         { *m = SearchNodesRequest{} }
func (m *SearchNodesRequest) String() string { return proto.CompactTextString(m) }
func (*SearchNodesRequest) ProtoMessage()    {}
func (*SearchNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{16}
}

func (m *SearchNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchNodesRequest.Unmarshal(m, b)
}
func (m *SearchNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchNodesRequest.Marshal(b, m, deterministic)
}
func (m *SearchNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchNodesRequest.Merge(m, src)
}
func (m *SearchNodesRequest) XXX_Size() int {
	return xxx_messageInfo_SearchNodesRequest.Size(m)
}
func (m *SearchNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchNodesRequest proto.InternalMessageInfo

func (m *SearchNodesRequest) GetFilter() *Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type SearchNodesResponse struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchNodesResponse) Reset()         { *m = SearchNodesResponse{} }
func (m *SearchNodesResponse) String() string { return proto.CompactTextString(m) }
func (*SearchNodesResponse) ProtoMessage()    {}
func (*SearchNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{17}
}

func (m *SearchNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchNodesResponse.Unmarshal(m, b)
}
func (m *SearchNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchNodesResponse.Marshal(b, m, deterministic)
}
func (m *SearchNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchNodesResponse.Merge(m, src)
}
func (m *SearchNodesResponse) XXX_Size() int {
	return xxx_messageInfo_SearchNodesResponse.Size(m)
}
func (m *SearchNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchNodesResponse proto.InternalMessageInfo

func (m *SearchNodesResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type SearchEdgesRequest struct {
	Filter               *Filter  `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchEdgesRequest) Reset()         { *m = SearchEdgesRequest{} }
func (m *SearchEdgesRequest) String() string { return proto.CompactTextString(m) }
func (*SearchEdgesRequest) ProtoMessage()    {}
func (*SearchEdgesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{18}
}

func (m *SearchEdgesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchEdgesRequest.Unmarshal(m, b)
}
func (m *SearchEdgesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchEdgesRequest.Marshal(b, m, deterministic)
}
func (m *SearchEdgesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchEdgesRequest.Merge(m, src)
}
func (m *SearchEdgesRequest) XXX_Size() int {
	return xxx_messageInfo_SearchEdgesRequest.Size(m)
}
func (m *SearchEdgesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchEdgesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchEdgesRequest proto.InternalMessageInfo

func (m *SearchEdgesRequest) GetFilter() *Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type SearchEdgesResponse struct {
	Edges                []*Edge  `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchEdgesResponse) Reset()         { *m = SearchEdgesResponse{} }
func (m *SearchEdgesResponse) String() string { return proto.CompactTextString(m) }
func (*SearchEdgesResponse) ProtoMessage()    {}
func (*SearchEdgesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{19}
}

func (m *SearchEdgesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchEdgesResponse.Unmarshal(m, b)
}
func (m *SearchEdgesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchEdgesResponse.Marshal(b, m, deterministic)
}
func (m *SearchEdgesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchEdgesResponse.Merge(m, src)
}
func (m *SearchEdgesResponse) XXX_Size() int {
	return xxx_messageInfo_SearchEdgesResponse.Size(m)
}
func (m *SearchEdgesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchEdgesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchEdgesResponse proto.InternalMessageInfo

func (m *SearchEdgesResponse) GetEdges() []*Edge {
	if m != nil {
		return m.Edges
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.Op", Op_name, Op_value)
	proto.RegisterEnum("api.Keyword", Keyword_name, Keyword_value)
	proto.RegisterType((*Command)(nil), "api.Command")
	proto.RegisterType((*Counter)(nil), "api.Counter")
	proto.RegisterType((*Path)(nil), "api.Path")
	proto.RegisterType((*Node)(nil), "api.Node")
	proto.RegisterType((*Message)(nil), "api.Message")
	proto.RegisterType((*Filter)(nil), "api.Filter")
	proto.RegisterType((*Export)(nil), "api.Export")
	proto.RegisterType((*Patch)(nil), "api.Patch")
	proto.RegisterType((*Edge)(nil), "api.Edge")
	proto.RegisterType((*EdgeFilters)(nil), "api.EdgeFilters")
	proto.RegisterType((*RaftJoinRequest)(nil), "api.RaftJoinRequest")
	proto.RegisterType((*RaftJoinResponse)(nil), "api.RaftJoinResponse")
	proto.RegisterType((*GetJWKSRequest)(nil), "api.GetJWKSRequest")
	proto.RegisterType((*GetJWKSResponse)(nil), "api.GetJWKSResponse")
	proto.RegisterMapType((map[string]string)(nil), "api.GetJWKSResponse.JwksEntry")
	proto.RegisterType((*UpdateJWKSRequest)(nil), "api.UpdateJWKSRequest")
	proto.RegisterMapType((map[string]string)(nil), "api.UpdateJWKSRequest.JwksEntry")
	proto.RegisterType((*UpdateJWKSResponse)(nil), "api.UpdateJWKSResponse")
	proto.RegisterMapType((map[string]string)(nil), "api.UpdateJWKSResponse.JwksEntry")
	proto.RegisterType((*SearchNodesRequest)(nil), "api.SearchNodesRequest")
	proto.RegisterType((*SearchNodesResponse)(nil), "api.SearchNodesResponse")
	proto.RegisterType((*SearchEdgesRequest)(nil), "api.SearchEdgesRequest")
	proto.RegisterType((*SearchEdgesResponse)(nil), "api.SearchEdgesResponse")
}

func init() { proto.RegisterFile("api/graphik.proto", fileDescriptor_063490d3009de3e6) }

var fileDescriptor_063490d3009de3e6 = []byte{
	// 946 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdd, 0x4e, 0x1b, 0x47,
	0x14, 0xf6, 0xee, 0xda, 0x5e, 0x7c, 0x5c, 0x81, 0x33, 0xa1, 0xc1, 0xb1, 0xda, 0x42, 0xa7, 0x52,
	0x84, 0x90, 0x6a, 0x24, 0xb7, 0x4d, 0x42, 0x6f, 0x2a, 0x07, 0x2f, 0x29, 0x24, 0x05, 0x34, 0x18,
	0x55, 0xed, 0x0d, 0x1a, 0xbc, 0x83, 0xbd, 0xc5, 0xde, 0x99, 0xee, 0x8e, 0x21, 0xbe, 0xe9, 0x45,
	0x95, 0x67, 0xe9, 0xc3, 0xf4, 0xba, 0x0f, 0x54, 0xcd, 0xcf, 0xe2, 0xb5, 0x4d, 0xe5, 0x14, 0xe5,
	0x6e, 0xce, 0x39, 0xdf, 0xf9, 0xff, 0xce, 0xc0, 0x23, 0x2a, 0xa2, 0xdd, 0x7e, 0x42, 0xc5, 0x20,
	0xba, 0x6e, 0x8a, 0x84, 0x4b, 0x8e, 0x3c, 0x2a, 0xa2, 0xc6, 0x67, 0x7d, 0xce, 0xfb, 0x43, 0xb6,
	0xab, 0x55, 0x97, 0xe3, 0xab, 0xdd, 0x54, 0x26, 0xe3, 0x9e, 0x34, 0x90, 0xc6, 0xe6, 0xbc, 0x55,
	0x46, 0x23, 0x96, 0x4a, 0x3a, 0x12, 0x16, 0xf0, 0x74, 0x1e, 0x40, 0xe3, 0x89, 0x31, 0xe1, 0xf7,
	0x0e, 0xf8, 0xfb, 0x7c, 0x34, 0xa2, 0x71, 0x88, 0x36, 0xc0, 0xe5, 0xa2, 0xee, 0x6c, 0x39, 0xdb,
	0xab, 0x2d, 0xbf, 0x49, 0x45, 0xd4, 0x3c, 0x11, 0xc4, 0xe5, 0x02, 0x3d, 0x03, 0xef, 0x86, 0x0e,
	0xeb, 0xee, 0x96, 0xb3, 0x5d, 0x6d, 0xad, 0x37, 0x4d, 0xb4, 0x66, 0x16, 0xad, 0xd9, 0x8e, 0x27,
	0x44, 0x01, 0xd0, 0x4b, 0xa8, 0xdc, 0xa5, 0xae, 0x7b, 0x1a, 0xdd, 0x58, 0x40, 0x77, 0x33, 0x04,
	0x99, 0x82, 0xf1, 0xa6, 0xaa, 0x62, 0x1c, 0x4b, 0x96, 0xa0, 0x75, 0x28, 0xf5, 0xd4, 0x53, 0x17,
	0xe2, 0x11, 0x23, 0xe0, 0x1d, 0x28, 0x9e, 0x52, 0x39, 0x40, 0x08, 0x8a, 0xdd, 0x89, 0x60, 0xda,
	0x58, 0x21, 0xfa, 0x8d, 0x56, 0xc1, 0x3d, 0xec, 0xe8, 0xea, 0x2a, 0xc4, 0x3d, 0xec, 0xe0, 0x7f,
	0x1c, 0x28, 0x1e, 0xf3, 0x90, 0xa1, 0xcf, 0xa1, 0x28, 0xa8, 0x1c, 0x68, 0x70, 0xb5, 0x55, 0xd1,
	0x2d, 0xa9, 0x28, 0x44, 0xab, 0xd1, 0x0b, 0x00, 0x2a, 0x65, 0x12, 0x5d, 0x8e, 0x25, 0x4b, 0x6d,
	0x77, 0x1b, 0x0b, 0xf5, 0x9e, 0xe9, 0x51, 0x93, 0x1c, 0x14, 0xed, 0x01, 0xf4, 0x12, 0x46, 0x25,
	0x0b, 0x2f, 0xa8, 0xfc, 0x90, 0x46, 0x2d, 0xba, 0x2d, 0x95, 0xeb, 0x58, 0x84, 0x99, 0x6b, 0x71,
	0xb9, 0xab, 0x45, 0xb7, 0x25, 0x16, 0xe0, 0xff, 0xc4, 0xd2, 0x94, 0xf6, 0x19, 0xaa, 0x83, 0xdf,
	0x1b, 0xd0, 0x38, 0x66, 0x43, 0x3b, 0x88, 0x4c, 0x54, 0xf3, 0x91, 0x6a, 0x3e, 0x66, 0x1a, 0xfa,
	0x3d, 0xd7, 0xa7, 0xf7, 0xc1, 0x7d, 0xe2, 0x2e, 0x94, 0x0f, 0xa2, 0xa1, 0x5a, 0x4a, 0x16, 0xd6,
	0xc9, 0x85, 0xdd, 0x82, 0x2a, 0x7b, 0x27, 0x12, 0x96, 0xa6, 0x11, 0x8f, 0xd5, 0xfc, 0xbc, 0xed,
	0x0a, 0xc9, 0xab, 0xd4, 0x2a, 0x87, 0xd1, 0x28, 0x32, 0x23, 0x2a, 0x11, 0x23, 0xe0, 0x23, 0x28,
	0x07, 0xef, 0x04, 0x4f, 0x24, 0xda, 0x84, 0x52, 0xcc, 0x43, 0x96, 0xd6, 0x9d, 0x2d, 0xef, 0x6e,
	0x41, 0x6a, 0x73, 0xc4, 0xe8, 0x15, 0x80, 0x85, 0x7d, 0x66, 0x82, 0x67, 0x80, 0x20, 0xec, 0x33,
	0x62, 0xf4, 0xf8, 0x1c, 0x4a, 0xa7, 0x54, 0xf6, 0x06, 0xcb, 0x56, 0xfd, 0x35, 0x94, 0x84, 0xc2,
	0x2d, 0xdb, 0xb2, 0x41, 0xe1, 0xbf, 0x5c, 0x28, 0xaa, 0x34, 0xcb, 0xc2, 0x3e, 0x81, 0xf2, 0x68,
	0x2c, 0xc7, 0xf6, 0x36, 0x56, 0x88, 0x95, 0x1e, 0x3c, 0x71, 0x95, 0xef, 0x2a, 0xe1, 0x23, 0x4b,
	0x8c, 0x7c, 0x3e, 0xa5, 0x46, 0x4f, 0xc1, 0x95, 0xbc, 0x5e, 0x9a, 0x37, 0xba, 0x92, 0xcf, 0x71,
	0xb2, 0xfc, 0x70, 0x4e, 0xfa, 0xff, 0x87, 0x93, 0x14, 0xaa, 0x6a, 0x4e, 0x86, 0x25, 0x29, 0xda,
	0x01, 0xd0, 0x7b, 0xb9, 0xd0, 0x4d, 0x98, 0xad, 0x56, 0x75, 0x9d, 0x06, 0x41, 0x2a, 0xda, 0x7c,
	0xa0, 0x7a, 0x79, 0x06, 0x2b, 0x06, 0x2b, 0xb9, 0x5d, 0xef, 0x0c, 0xd2, 0xd7, 0xc6, 0x2e, 0xc7,
	0x1d, 0x58, 0x23, 0xf4, 0x4a, 0x1e, 0xf1, 0x28, 0x26, 0xec, 0xf7, 0x31, 0x4b, 0x25, 0xda, 0x00,
	0x5f, 0xf1, 0xe3, 0x22, 0x0a, 0x2d, 0x21, 0xcb, 0x4a, 0x3c, 0x0c, 0xd5, 0x5d, 0xd0, 0x30, 0x54,
	0xfc, 0xb3, 0x07, 0x90, 0x89, 0x18, 0x41, 0x6d, 0x1a, 0x25, 0x15, 0x3c, 0x4e, 0x19, 0xae, 0xc1,
	0xea, 0x6b, 0x26, 0x8f, 0x7e, 0x7e, 0x73, 0x66, 0x03, 0xe3, 0x3f, 0x60, 0xed, 0x4e, 0x63, 0x40,
	0xa8, 0x05, 0xc5, 0xdf, 0x6e, 0xaf, 0x33, 0x8a, 0x7e, 0xa1, 0x4b, 0x9c, 0xc3, 0x34, 0x8f, 0x6e,
	0xaf, 0xd3, 0x20, 0x96, 0xc9, 0x84, 0x68, 0x6c, 0xe3, 0x05, 0x54, 0xee, 0x54, 0xa8, 0x06, 0xde,
	0x35, 0x9b, 0xd8, 0x42, 0xd5, 0x53, 0x9d, 0xc5, 0x0d, 0x1d, 0x8e, 0xb3, 0x23, 0x35, 0xc2, 0xf7,
	0xee, 0x4b, 0x07, 0xff, 0xe9, 0xc0, 0xa3, 0x73, 0x3d, 0xdc, 0x5c, 0x55, 0xe8, 0xdb, 0x99, 0x12,
	0xb6, 0x74, 0x09, 0x0b, 0xa8, 0x8f, 0x57, 0xc4, 0x7b, 0x07, 0x50, 0x3e, 0xbc, 0x1d, 0xc4, 0x77,
	0x33, 0x55, 0x7c, 0xb9, 0x50, 0xc5, 0xc7, 0x9e, 0xc5, 0x1e, 0xa0, 0x33, 0x46, 0x93, 0xde, 0x40,
	0x7d, 0x08, 0x69, 0x36, 0x8b, 0xaf, 0xa0, 0x7c, 0xa5, 0x09, 0x62, 0x4f, 0x72, 0x86, 0x33, 0xd6,
	0x84, 0x9f, 0xc3, 0xe3, 0x19, 0x57, 0xdb, 0xc1, 0xb2, 0xef, 0x66, 0x9a, 0x52, 0x71, 0xfa, 0x81,
	0x29, 0xad, 0xeb, 0x34, 0xa5, 0xf9, 0xc0, 0x9c, 0xfb, 0x3f, 0xb0, 0x9d, 0x01, 0xb8, 0x27, 0x02,
	0xad, 0x41, 0x75, 0x9f, 0x04, 0xed, 0x6e, 0x70, 0x71, 0x7c, 0xd2, 0x09, 0x6a, 0x05, 0xb4, 0x0a,
	0x70, 0xda, 0xee, 0xee, 0xff, 0x68, 0x64, 0x47, 0x01, 0x3a, 0xc1, 0xdb, 0x20, 0x03, 0xb8, 0x39,
	0x8f, 0xa0, 0xf3, 0x3a, 0xa8, 0x79, 0x53, 0x0f, 0x2d, 0x17, 0x73, 0x1e, 0x5a, 0x51, 0xda, 0xd9,
	0x04, 0xff, 0x0d, 0x9b, 0xdc, 0xf2, 0x24, 0x44, 0x3e, 0x78, 0xed, 0xe3, 0x5f, 0x6a, 0x05, 0x54,
	0x05, 0xbf, 0x13, 0x1c, 0xb4, 0xcf, 0xdf, 0x76, 0x6b, 0x4e, 0xeb, 0x6f, 0x17, 0x3e, 0x69, 0x87,
	0xa3, 0x28, 0x3e, 0x63, 0xc9, 0x4d, 0xd4, 0x63, 0x68, 0x0f, 0x56, 0xb2, 0x9b, 0x41, 0xeb, 0xba,
	0xf2, 0xb9, 0x43, 0x6c, 0x7c, 0x3a, 0xa7, 0xb5, 0x87, 0x55, 0x40, 0xcf, 0xc1, 0xb7, 0x47, 0x82,
	0x1e, 0xcf, 0x9e, 0x8c, 0x71, 0x5c, 0xbf, 0xef, 0x8e, 0x70, 0x01, 0xfd, 0x00, 0x30, 0xe5, 0x14,
	0x7a, 0x72, 0x3f, 0xd5, 0x1b, 0x1b, 0xff, 0x41, 0x3e, 0x5c, 0x40, 0xaf, 0xa0, 0x9a, 0x5b, 0x3d,
	0x32, 0xc8, 0x45, 0x1e, 0x35, 0xea, 0x8b, 0x86, 0xc5, 0x18, 0x7a, 0x97, 0x33, 0x31, 0xf2, 0xc4,
	0x98, 0x89, 0x31, 0xb3, 0x76, 0x5c, 0x78, 0xe5, 0xff, 0x5a, 0xa2, 0x22, 0x12, 0x97, 0x97, 0x65,
	0xfd, 0x81, 0x7e, 0xf3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x77, 0xac, 0x0e, 0xdb, 0x09,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminServiceClient interface {
	RaftJoin(ctx context.Context, in *RaftJoinRequest, opts ...grpc.CallOption) (*RaftJoinResponse, error)
	GetJWKS(ctx context.Context, in *GetJWKSRequest, opts ...grpc.CallOption) (*GetJWKSResponse, error)
	UpdateJWKS(ctx context.Context, in *UpdateJWKSRequest, opts ...grpc.CallOption) (*UpdateJWKSResponse, error)
	SearchNodes(ctx context.Context, in *SearchNodesRequest, opts ...grpc.CallOption) (*SearchNodesResponse, error)
	SearchEdges(ctx context.Context, in *SearchEdgesRequest, opts ...grpc.CallOption) (*SearchEdgesResponse, error)
}

type adminServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdminServiceClient(cc *grpc.ClientConn) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) RaftJoin(ctx context.Context, in *RaftJoinRequest, opts ...grpc.CallOption) (*RaftJoinResponse, error) {
	out := new(RaftJoinResponse)
	err := c.cc.Invoke(ctx, "/api.AdminService/RaftJoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetJWKS(ctx context.Context, in *GetJWKSRequest, opts ...grpc.CallOption) (*GetJWKSResponse, error) {
	out := new(GetJWKSResponse)
	err := c.cc.Invoke(ctx, "/api.AdminService/GetJWKS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateJWKS(ctx context.Context, in *UpdateJWKSRequest, opts ...grpc.CallOption) (*UpdateJWKSResponse, error) {
	out := new(UpdateJWKSResponse)
	err := c.cc.Invoke(ctx, "/api.AdminService/UpdateJWKS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SearchNodes(ctx context.Context, in *SearchNodesRequest, opts ...grpc.CallOption) (*SearchNodesResponse, error) {
	out := new(SearchNodesResponse)
	err := c.cc.Invoke(ctx, "/api.AdminService/SearchNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SearchEdges(ctx context.Context, in *SearchEdgesRequest, opts ...grpc.CallOption) (*SearchEdgesResponse, error) {
	out := new(SearchEdgesResponse)
	err := c.cc.Invoke(ctx, "/api.AdminService/SearchEdges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
type AdminServiceServer interface {
	RaftJoin(context.Context, *RaftJoinRequest) (*RaftJoinResponse, error)
	GetJWKS(context.Context, *GetJWKSRequest) (*GetJWKSResponse, error)
	UpdateJWKS(context.Context, *UpdateJWKSRequest) (*UpdateJWKSResponse, error)
	SearchNodes(context.Context, *SearchNodesRequest) (*SearchNodesResponse, error)
	SearchEdges(context.Context, *SearchEdgesRequest) (*SearchEdgesResponse, error)
}

func RegisterAdminServiceServer(s *grpc.Server, srv AdminServiceServer) {
	s.RegisterService(&_AdminService_serviceDesc, srv)
}

func _AdminService_RaftJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RaftJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AdminService/RaftJoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RaftJoin(ctx, req.(*RaftJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetJWKS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJWKSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetJWKS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AdminService/GetJWKS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetJWKS(ctx, req.(*GetJWKSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateJWKS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJWKSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateJWKS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AdminService/UpdateJWKS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateJWKS(ctx, req.(*UpdateJWKSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SearchNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SearchNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AdminService/SearchNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SearchNodes(ctx, req.(*SearchNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SearchEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SearchEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AdminService/SearchEdges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SearchEdges(ctx, req.(*SearchEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RaftJoin",
			Handler:    _AdminService_RaftJoin_Handler,
		},
		{
			MethodName: "GetJWKS",
			Handler:    _AdminService_GetJWKS_Handler,
		},
		{
			MethodName: "UpdateJWKS",
			Handler:    _AdminService_UpdateJWKS_Handler,
		},
		{
			MethodName: "SearchNodes",
			Handler:    _AdminService_SearchNodes_Handler,
		},
		{
			MethodName: "SearchEdges",
			Handler:    _AdminService_SearchEdges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/graphik.proto",
}
