// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/graphik.proto

package apipb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	_struct "github.com/golang/protobuf/ptypes/struct"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Op int32

const (
	Op_CREATE_NODES Op = 0
	Op_PATCH_NODES  Op = 1
	Op_DELETE_NODES Op = 2
	Op_CREATE_EDGES Op = 3
	Op_PATCH_EDGES  Op = 4
	Op_DELETE_EDGES Op = 5
	Op_SET_AUTH     Op = 6
)

var Op_name = map[int32]string{
	0: "CREATE_NODES",
	1: "PATCH_NODES",
	2: "DELETE_NODES",
	3: "CREATE_EDGES",
	4: "PATCH_EDGES",
	5: "DELETE_EDGES",
	6: "SET_AUTH",
}

var Op_value = map[string]int32{
	"CREATE_NODES": 0,
	"PATCH_NODES":  1,
	"DELETE_NODES": 2,
	"CREATE_EDGES": 3,
	"PATCH_EDGES":  4,
	"DELETE_EDGES": 5,
	"SET_AUTH":     6,
}

func (x Op) String() string {
	return proto.EnumName(Op_name, int32(x))
}

func (Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{0}
}

type Cascade int32

const (
	Cascade_CASCADE_NONE   Cascade = 0
	Cascade_CASCADE_FROM   Cascade = 1
	Cascade_CASCADE_TO     Cascade = 2
	Cascade_CASCADE_MUTUAL Cascade = 3
)

var Cascade_name = map[int32]string{
	0: "CASCADE_NONE",
	1: "CASCADE_FROM",
	2: "CASCADE_TO",
	3: "CASCADE_MUTUAL",
}

var Cascade_value = map[string]int32{
	"CASCADE_NONE":   0,
	"CASCADE_FROM":   1,
	"CASCADE_TO":     2,
	"CASCADE_MUTUAL": 3,
}

func (x Cascade) String() string {
	return proto.EnumName(Cascade_name, int32(x))
}

func (Cascade) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{1}
}

type Keyword int32

const (
	Keyword_INVALID Keyword = 0
	Keyword_ANY     Keyword = 1
	Keyword_DEFAULT Keyword = 2
)

var Keyword_name = map[int32]string{
	0: "INVALID",
	1: "ANY",
	2: "DEFAULT",
}

var Keyword_value = map[string]int32{
	"INVALID": 0,
	"ANY":     1,
	"DEFAULT": 2,
}

func (x Keyword) String() string {
	return proto.EnumName(Keyword_name, int32(x))
}

func (Keyword) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{2}
}

type Path struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{0}
}

func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (m *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(m, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Path) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Node struct {
	Type                 string          `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string          `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Attributes           *_struct.Struct `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	CreatedAt            int64           `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64           `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetAttributes() *_struct.Struct {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Node) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Node) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Edge struct {
	Type                 string          `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string          `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Attributes           *_struct.Struct `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Cascade              Cascade         `protobuf:"varint,4,opt,name=cascade,proto3,enum=api.Cascade" json:"cascade,omitempty"`
	From                 *Path           `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Path           `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	CreatedAt            int64           `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64           `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Edge) Reset()         { *m = Edge{} }
func (m *Edge) String() string { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()    {}
func (*Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{2}
}

func (m *Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Edge.Unmarshal(m, b)
}
func (m *Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Edge.Marshal(b, m, deterministic)
}
func (m *Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Edge.Merge(m, src)
}
func (m *Edge) XXX_Size() int {
	return xxx_messageInfo_Edge.Size(m)
}
func (m *Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Edge proto.InternalMessageInfo

func (m *Edge) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Edge) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Edge) GetAttributes() *_struct.Struct {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Edge) GetCascade() Cascade {
	if m != nil {
		return m.Cascade
	}
	return Cascade_CASCADE_NONE
}

func (m *Edge) GetFrom() *Path {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Edge) GetTo() *Path {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Edge) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Edge) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type TypeFilter struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Expressions          []string `protobuf:"bytes,2,rep,name=expressions,proto3" json:"expressions,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeFilter) Reset()         { *m = TypeFilter{} }
func (m *TypeFilter) String() string { return proto.CompactTextString(m) }
func (*TypeFilter) ProtoMessage()    {}
func (*TypeFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{3}
}

func (m *TypeFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeFilter.Unmarshal(m, b)
}
func (m *TypeFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeFilter.Marshal(b, m, deterministic)
}
func (m *TypeFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeFilter.Merge(m, src)
}
func (m *TypeFilter) XXX_Size() int {
	return xxx_messageInfo_TypeFilter.Size(m)
}
func (m *TypeFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeFilter.DiscardUnknown(m)
}

var xxx_messageInfo_TypeFilter proto.InternalMessageInfo

func (m *TypeFilter) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TypeFilter) GetExpressions() []string {
	if m != nil {
		return m.Expressions
	}
	return nil
}

func (m *TypeFilter) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type PathFilter struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Expressions          []string `protobuf:"bytes,3,rep,name=expressions,proto3" json:"expressions,omitempty"`
	Limit                int32    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PathFilter) Reset()         { *m = PathFilter{} }
func (m *PathFilter) String() string { return proto.CompactTextString(m) }
func (*PathFilter) ProtoMessage()    {}
func (*PathFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{4}
}

func (m *PathFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathFilter.Unmarshal(m, b)
}
func (m *PathFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathFilter.Marshal(b, m, deterministic)
}
func (m *PathFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathFilter.Merge(m, src)
}
func (m *PathFilter) XXX_Size() int {
	return xxx_messageInfo_PathFilter.Size(m)
}
func (m *PathFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_PathFilter.DiscardUnknown(m)
}

var xxx_messageInfo_PathFilter proto.InternalMessageInfo

func (m *PathFilter) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PathFilter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PathFilter) GetExpressions() []string {
	if m != nil {
		return m.Expressions
	}
	return nil
}

func (m *PathFilter) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Command struct {
	Op                   Op       `protobuf:"varint,1,opt,name=op,proto3,enum=api.Op" json:"op,omitempty"`
	Val                  *any.Any `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{5}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetOp() Op {
	if m != nil {
		return m.Op
	}
	return Op_CREATE_NODES
}

func (m *Command) GetVal() *any.Any {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *Command) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Export struct {
	Nodes                []*_struct.Struct `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges                []*_struct.Struct `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Export) Reset()         { *m = Export{} }
func (m *Export) String() string { return proto.CompactTextString(m) }
func (*Export) ProtoMessage()    {}
func (*Export) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{6}
}

func (m *Export) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Export.Unmarshal(m, b)
}
func (m *Export) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Export.Marshal(b, m, deterministic)
}
func (m *Export) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Export.Merge(m, src)
}
func (m *Export) XXX_Size() int {
	return xxx_messageInfo_Export.Size(m)
}
func (m *Export) XXX_DiscardUnknown() {
	xxx_messageInfo_Export.DiscardUnknown(m)
}

var xxx_messageInfo_Export proto.InternalMessageInfo

func (m *Export) GetNodes() []*_struct.Struct {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Export) GetEdges() []*_struct.Struct {
	if m != nil {
		return m.Edges
	}
	return nil
}

type Pong struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{7}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RaftNode struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftNode) Reset()         { *m = RaftNode{} }
func (m *RaftNode) String() string { return proto.CompactTextString(m) }
func (*RaftNode) ProtoMessage()    {}
func (*RaftNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{8}
}

func (m *RaftNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftNode.Unmarshal(m, b)
}
func (m *RaftNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftNode.Marshal(b, m, deterministic)
}
func (m *RaftNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftNode.Merge(m, src)
}
func (m *RaftNode) XXX_Size() int {
	return xxx_messageInfo_RaftNode.Size(m)
}
func (m *RaftNode) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftNode.DiscardUnknown(m)
}

var xxx_messageInfo_RaftNode proto.InternalMessageInfo

func (m *RaftNode) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *RaftNode) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type AuthConfig struct {
	JwksSources          []string `protobuf:"bytes,1,rep,name=jwks_sources,json=jwksSources,proto3" json:"jwks_sources,omitempty"`
	AuthExpressions      []string `protobuf:"bytes,2,rep,name=auth_expressions,json=authExpressions,proto3" json:"auth_expressions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthConfig) Reset()         { *m = AuthConfig{} }
func (m *AuthConfig) String() string { return proto.CompactTextString(m) }
func (*AuthConfig) ProtoMessage()    {}
func (*AuthConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{9}
}

func (m *AuthConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthConfig.Unmarshal(m, b)
}
func (m *AuthConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthConfig.Marshal(b, m, deterministic)
}
func (m *AuthConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthConfig.Merge(m, src)
}
func (m *AuthConfig) XXX_Size() int {
	return xxx_messageInfo_AuthConfig.Size(m)
}
func (m *AuthConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AuthConfig proto.InternalMessageInfo

func (m *AuthConfig) GetJwksSources() []string {
	if m != nil {
		return m.JwksSources
	}
	return nil
}

func (m *AuthConfig) GetAuthExpressions() []string {
	if m != nil {
		return m.AuthExpressions
	}
	return nil
}

type RaftConfig struct {
	Bind                 string   `protobuf:"bytes,1,opt,name=bind,proto3" json:"bind,omitempty"`
	StoragePath          string   `protobuf:"bytes,2,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	Join                 string   `protobuf:"bytes,3,opt,name=join,proto3" json:"join,omitempty"`
	NodeId               string   `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftConfig) Reset()         { *m = RaftConfig{} }
func (m *RaftConfig) String() string { return proto.CompactTextString(m) }
func (*RaftConfig) ProtoMessage()    {}
func (*RaftConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{10}
}

func (m *RaftConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftConfig.Unmarshal(m, b)
}
func (m *RaftConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftConfig.Marshal(b, m, deterministic)
}
func (m *RaftConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftConfig.Merge(m, src)
}
func (m *RaftConfig) XXX_Size() int {
	return xxx_messageInfo_RaftConfig.Size(m)
}
func (m *RaftConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RaftConfig proto.InternalMessageInfo

func (m *RaftConfig) GetBind() string {
	if m != nil {
		return m.Bind
	}
	return ""
}

func (m *RaftConfig) GetStoragePath() string {
	if m != nil {
		return m.StoragePath
	}
	return ""
}

func (m *RaftConfig) GetJoin() string {
	if m != nil {
		return m.Join
	}
	return ""
}

func (m *RaftConfig) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type HTTPConfig struct {
	Bind                 string   `protobuf:"bytes,1,opt,name=bind,proto3" json:"bind,omitempty"`
	AllowedOrigins       []string `protobuf:"bytes,2,rep,name=allowed_origins,json=allowedOrigins,proto3" json:"allowed_origins,omitempty"`
	AllowedHeaders       []string `protobuf:"bytes,3,rep,name=allowed_headers,json=allowedHeaders,proto3" json:"allowed_headers,omitempty"`
	AllowedMethods       []string `protobuf:"bytes,4,rep,name=allowed_methods,json=allowedMethods,proto3" json:"allowed_methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPConfig) Reset()         { *m = HTTPConfig{} }
func (m *HTTPConfig) String() string { return proto.CompactTextString(m) }
func (*HTTPConfig) ProtoMessage()    {}
func (*HTTPConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{11}
}

func (m *HTTPConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPConfig.Unmarshal(m, b)
}
func (m *HTTPConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPConfig.Marshal(b, m, deterministic)
}
func (m *HTTPConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPConfig.Merge(m, src)
}
func (m *HTTPConfig) XXX_Size() int {
	return xxx_messageInfo_HTTPConfig.Size(m)
}
func (m *HTTPConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPConfig.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPConfig proto.InternalMessageInfo

func (m *HTTPConfig) GetBind() string {
	if m != nil {
		return m.Bind
	}
	return ""
}

func (m *HTTPConfig) GetAllowedOrigins() []string {
	if m != nil {
		return m.AllowedOrigins
	}
	return nil
}

func (m *HTTPConfig) GetAllowedHeaders() []string {
	if m != nil {
		return m.AllowedHeaders
	}
	return nil
}

func (m *HTTPConfig) GetAllowedMethods() []string {
	if m != nil {
		return m.AllowedMethods
	}
	return nil
}

type GRPCConfig struct {
	Bind                 string   `protobuf:"bytes,1,opt,name=bind,proto3" json:"bind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GRPCConfig) Reset()         { *m = GRPCConfig{} }
func (m *GRPCConfig) String() string { return proto.CompactTextString(m) }
func (*GRPCConfig) ProtoMessage()    {}
func (*GRPCConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{12}
}

func (m *GRPCConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GRPCConfig.Unmarshal(m, b)
}
func (m *GRPCConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GRPCConfig.Marshal(b, m, deterministic)
}
func (m *GRPCConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GRPCConfig.Merge(m, src)
}
func (m *GRPCConfig) XXX_Size() int {
	return xxx_messageInfo_GRPCConfig.Size(m)
}
func (m *GRPCConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GRPCConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GRPCConfig proto.InternalMessageInfo

func (m *GRPCConfig) GetBind() string {
	if m != nil {
		return m.Bind
	}
	return ""
}

type Config struct {
	Http                 *HTTPConfig `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc                 *GRPCConfig `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Raft                 *RaftConfig `protobuf:"bytes,3,opt,name=raft,proto3" json:"raft,omitempty"`
	Auth                 *AuthConfig `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_063490d3009de3e6, []int{13}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetHttp() *HTTPConfig {
	if m != nil {
		return m.Http
	}
	return nil
}

func (m *Config) GetGrpc() *GRPCConfig {
	if m != nil {
		return m.Grpc
	}
	return nil
}

func (m *Config) GetRaft() *RaftConfig {
	if m != nil {
		return m.Raft
	}
	return nil
}

func (m *Config) GetAuth() *AuthConfig {
	if m != nil {
		return m.Auth
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.Op", Op_name, Op_value)
	proto.RegisterEnum("api.Cascade", Cascade_name, Cascade_value)
	proto.RegisterEnum("api.Keyword", Keyword_name, Keyword_value)
	proto.RegisterType((*Path)(nil), "api.Path")
	proto.RegisterType((*Node)(nil), "api.Node")
	proto.RegisterType((*Edge)(nil), "api.Edge")
	proto.RegisterType((*TypeFilter)(nil), "api.TypeFilter")
	proto.RegisterType((*PathFilter)(nil), "api.PathFilter")
	proto.RegisterType((*Command)(nil), "api.Command")
	proto.RegisterType((*Export)(nil), "api.Export")
	proto.RegisterType((*Pong)(nil), "api.Pong")
	proto.RegisterType((*RaftNode)(nil), "api.RaftNode")
	proto.RegisterType((*AuthConfig)(nil), "api.AuthConfig")
	proto.RegisterType((*RaftConfig)(nil), "api.RaftConfig")
	proto.RegisterType((*HTTPConfig)(nil), "api.HTTPConfig")
	proto.RegisterType((*GRPCConfig)(nil), "api.GRPCConfig")
	proto.RegisterType((*Config)(nil), "api.Config")
}

func init() { proto.RegisterFile("api/graphik.proto", fileDescriptor_063490d3009de3e6) }

var fileDescriptor_063490d3009de3e6 = []byte{
	// 959 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x5d, 0x73, 0xe3, 0x34,
	0x14, 0x8d, 0x3f, 0x12, 0x6f, 0xae, 0x4b, 0x6a, 0x34, 0x3b, 0x6c, 0xb6, 0xec, 0x0e, 0xc1, 0xcc,
	0x2c, 0xa5, 0xb0, 0xe9, 0x4c, 0x60, 0xe0, 0x89, 0x07, 0x93, 0xb8, 0x1f, 0xd0, 0x36, 0x41, 0x49,
	0x19, 0xd8, 0x97, 0x8c, 0x1a, 0x2b, 0x8e, 0x76, 0x13, 0x4b, 0x63, 0x2b, 0xed, 0x76, 0x86, 0x37,
	0x7e, 0x06, 0xbc, 0xf0, 0xb7, 0xf8, 0x35, 0x8c, 0x64, 0xbb, 0xc9, 0xa6, 0xdb, 0x0c, 0x2f, 0xbc,
	0x59, 0xe7, 0x1c, 0xe9, 0xde, 0x7b, 0xee, 0x95, 0x0c, 0x1f, 0x12, 0xc1, 0x0e, 0xe3, 0x94, 0x88,
	0x19, 0x7b, 0xd3, 0x16, 0x29, 0x97, 0x1c, 0x59, 0x44, 0xb0, 0xbd, 0x67, 0x31, 0xe7, 0xf1, 0x9c,
	0x1e, 0x6a, 0xe8, 0x6a, 0x39, 0x3d, 0xcc, 0x64, 0xba, 0x9c, 0xc8, 0x5c, 0xb2, 0xf7, 0xc9, 0x26,
	0x2b, 0xd9, 0x82, 0x66, 0x92, 0x2c, 0x44, 0x21, 0x78, 0xba, 0x29, 0x20, 0xc9, 0x6d, 0x41, 0x7d,
	0xbc, 0x49, 0xd1, 0x85, 0x90, 0x05, 0xe9, 0x1f, 0x80, 0x3d, 0x20, 0x72, 0x86, 0x10, 0xd8, 0xf2,
	0x56, 0xd0, 0xa6, 0xd1, 0x32, 0xf6, 0xeb, 0x58, 0x7f, 0xa3, 0x06, 0x98, 0x2c, 0x6a, 0x9a, 0x1a,
	0x31, 0x59, 0xe4, 0xff, 0x6d, 0x80, 0x7d, 0xc1, 0x23, 0xfa, 0x5f, 0xc4, 0xe8, 0x3b, 0x00, 0x22,
	0x65, 0xca, 0xae, 0x96, 0x92, 0x66, 0x4d, 0xab, 0x65, 0xec, 0xbb, 0x9d, 0x27, 0xed, 0x3c, 0x95,
	0x76, 0x99, 0x4a, 0x7b, 0xa8, 0x8b, 0xc4, 0x6b, 0x52, 0xf4, 0x1c, 0x60, 0x92, 0x52, 0x22, 0x69,
	0x34, 0x26, 0xb2, 0x69, 0xb7, 0x8c, 0x7d, 0x0b, 0xd7, 0x0b, 0x24, 0x90, 0x8a, 0x5e, 0x8a, 0xa8,
	0xa4, 0xab, 0x39, 0x5d, 0x20, 0x81, 0xf4, 0xff, 0x30, 0xc1, 0x0e, 0xa3, 0xf8, 0x7f, 0xce, 0xf1,
	0x05, 0x38, 0x13, 0x92, 0x4d, 0x48, 0x44, 0x75, 0x82, 0x8d, 0xce, 0x4e, 0x9b, 0x08, 0xd6, 0xee,
	0xe6, 0x18, 0x2e, 0x49, 0xf4, 0x1c, 0xec, 0x69, 0xca, 0x17, 0x3a, 0x4d, 0xb7, 0x53, 0xd7, 0x22,
	0x65, 0x37, 0xd6, 0x30, 0x7a, 0x0a, 0xa6, 0xe4, 0xcd, 0xda, 0x26, 0x69, 0x4a, 0xbe, 0xe1, 0x02,
	0x6c, 0x77, 0xc1, 0xdd, 0x74, 0xe1, 0x57, 0x80, 0xd1, 0xad, 0xa0, 0x47, 0x6c, 0x2e, 0x69, 0xfa,
	0x5e, 0x2b, 0x5a, 0xe0, 0xd2, 0xb7, 0x22, 0xa5, 0x59, 0xc6, 0x78, 0x92, 0x35, 0xcd, 0x96, 0xb5,
	0x5f, 0xc7, 0xeb, 0x10, 0x7a, 0x0c, 0xd5, 0x39, 0x5b, 0x30, 0xa9, 0x7d, 0xa9, 0xe2, 0x7c, 0xe1,
	0xcf, 0x00, 0x54, 0x8e, 0x5b, 0x4e, 0xde, 0x34, 0x79, 0x23, 0x92, 0xb5, 0x25, 0x92, 0xfd, 0x6e,
	0x24, 0xa7, 0xcb, 0x17, 0x0b, 0x92, 0x44, 0xe8, 0x09, 0x98, 0x5c, 0xe8, 0x20, 0x8d, 0x8e, 0xa3,
	0x7d, 0xea, 0x0b, 0x6c, 0x72, 0x81, 0x5e, 0x80, 0x75, 0x4d, 0xe6, 0x3a, 0x98, 0xdb, 0x79, 0x7c,
	0xaf, 0x73, 0x41, 0x72, 0x8b, 0x95, 0x00, 0x3d, 0x83, 0xfa, 0xdd, 0x85, 0xd1, 0xf5, 0x58, 0x78,
	0x05, 0xf8, 0x53, 0xa8, 0x85, 0x6f, 0x05, 0x4f, 0x25, 0x7a, 0x09, 0xd5, 0x84, 0x47, 0x34, 0x6b,
	0x1a, 0x2d, 0x6b, 0xdb, 0x2c, 0xe4, 0x2a, 0x25, 0xa7, 0x51, 0x4c, 0x73, 0xfb, 0xb6, 0xc9, 0xb5,
	0xca, 0x6f, 0x81, 0x3d, 0xe0, 0x49, 0x8c, 0x9a, 0xe0, 0x2c, 0x68, 0x96, 0x91, 0xb8, 0x34, 0xae,
	0x5c, 0xfa, 0xdf, 0xc3, 0x23, 0x4c, 0xa6, 0x52, 0x5f, 0xb2, 0x27, 0xe0, 0xa8, 0x28, 0x63, 0x16,
	0x15, 0xaa, 0x9a, 0x5a, 0x9e, 0x46, 0x6a, 0x3b, 0x89, 0x22, 0xe5, 0x5e, 0xe1, 0x72, 0xb9, 0xf4,
	0x5f, 0x01, 0x04, 0x4b, 0x39, 0xeb, 0xf2, 0x64, 0xca, 0x62, 0xf4, 0x29, 0xec, 0xbc, 0xbe, 0x79,
	0x93, 0x8d, 0x33, 0xbe, 0x4c, 0x27, 0x45, 0x4d, 0x75, 0xec, 0x2a, 0x6c, 0x98, 0x43, 0xe8, 0x0b,
	0xf0, 0xc8, 0x52, 0xce, 0xc6, 0xf7, 0x47, 0x61, 0x57, 0xe1, 0xe1, 0x0a, 0xf6, 0x05, 0x80, 0x4a,
	0xad, 0x38, 0x1b, 0x81, 0x7d, 0xc5, 0x92, 0x32, 0x33, 0xfd, 0xad, 0xe2, 0x65, 0x92, 0xa7, 0x24,
	0xa6, 0x63, 0x41, 0xe4, 0xac, 0x48, 0xce, 0x2d, 0xb0, 0xf2, 0x95, 0x79, 0xcd, 0x59, 0xa2, 0x5b,
	0x50, 0xc7, 0xfa, 0x7b, 0xbd, 0x4e, 0x7b, 0xbd, 0x4e, 0xff, 0x4f, 0x03, 0xe0, 0x64, 0x34, 0x1a,
	0x6c, 0x09, 0xf9, 0x39, 0xec, 0x92, 0xf9, 0x9c, 0xdf, 0xd0, 0x68, 0xcc, 0x53, 0x16, 0xb3, 0xbb,
	0xf4, 0x1b, 0x05, 0xdc, 0xcf, 0xd1, 0x75, 0xe1, 0x8c, 0x92, 0x88, 0xa6, 0xe5, 0x20, 0x96, 0xc2,
	0x93, 0x1c, 0x5d, 0x17, 0x2e, 0xa8, 0x9c, 0xf1, 0x28, 0x6b, 0xda, 0xef, 0x08, 0xcf, 0x73, 0xd4,
	0x6f, 0x01, 0x1c, 0xe3, 0x41, 0xf7, 0xe1, 0xe4, 0xfc, 0xbf, 0x0c, 0xa8, 0x15, 0xf4, 0x67, 0x60,
	0xcf, 0xa4, 0xcc, 0x47, 0xd8, 0xed, 0xec, 0xea, 0x11, 0x5e, 0x95, 0x86, 0x35, 0xa9, 0x44, 0x71,
	0x2a, 0x26, 0xc5, 0x34, 0xe7, 0xa2, 0x55, 0x08, 0xac, 0x49, 0x25, 0x4a, 0xc9, 0x54, 0x16, 0x8f,
	0x55, 0x2e, 0x5a, 0xf5, 0x05, 0x6b, 0x52, 0x89, 0x54, 0xfb, 0xb4, 0x9f, 0xa5, 0x68, 0x35, 0x18,
	0x58, 0x93, 0x07, 0xbf, 0x83, 0xd9, 0x17, 0xc8, 0x83, 0x9d, 0x2e, 0x0e, 0x83, 0x51, 0x38, 0xbe,
	0xe8, 0xf7, 0xc2, 0xa1, 0x57, 0x41, 0xbb, 0xe0, 0x0e, 0x82, 0x51, 0xf7, 0xa4, 0x00, 0x0c, 0x25,
	0xe9, 0x85, 0x67, 0xe1, 0x9d, 0xc4, 0x5c, 0xdb, 0x14, 0xf6, 0x8e, 0xc3, 0xa1, 0x67, 0xad, 0x36,
	0xe5, 0x80, 0xbd, 0xb6, 0x29, 0x47, 0xaa, 0x68, 0x07, 0x1e, 0x0d, 0xc3, 0xd1, 0x38, 0xb8, 0x1c,
	0x9d, 0x78, 0xb5, 0x83, 0x9f, 0xc1, 0x29, 0x5e, 0x4b, 0x7d, 0x5a, 0x30, 0xec, 0x06, 0x3d, 0x15,
	0xe0, 0x22, 0xf4, 0x2a, 0xeb, 0xc8, 0x11, 0xee, 0x9f, 0x7b, 0x06, 0x6a, 0x00, 0x94, 0xc8, 0xa8,
	0xef, 0x99, 0x08, 0x41, 0xa3, 0x5c, 0x9f, 0x5f, 0x8e, 0x2e, 0x83, 0x33, 0xcf, 0x3a, 0xf8, 0x0a,
	0x9c, 0x9f, 0xe8, 0xed, 0x0d, 0x4f, 0x23, 0xe4, 0x82, 0x73, 0x7a, 0xf1, 0x4b, 0x70, 0x76, 0xda,
	0xf3, 0x2a, 0xc8, 0x01, 0x2b, 0xb8, 0xf8, 0xcd, 0x33, 0x14, 0xda, 0x0b, 0x8f, 0x82, 0xcb, 0xb3,
	0x91, 0x67, 0x76, 0xfe, 0x31, 0xa0, 0x31, 0x48, 0xd9, 0x35, 0x91, 0x74, 0x48, 0xd3, 0x6b, 0x36,
	0xa1, 0xe8, 0x4b, 0xb0, 0x07, 0x2c, 0x89, 0xd1, 0x47, 0xf7, 0xee, 0x71, 0xa8, 0xfe, 0x98, 0x7b,
	0xc5, 0x13, 0xcd, 0x93, 0xd8, 0xaf, 0xa0, 0x6f, 0xc1, 0xfd, 0x91, 0xb3, 0xa4, 0x3b, 0x5f, 0x66,
	0xea, 0x25, 0xfc, 0xe0, 0xae, 0x13, 0xea, 0xf2, 0xee, 0x3d, 0x70, 0x84, 0x5f, 0x41, 0xdf, 0x80,
	0x73, 0x4c, 0xa5, 0xea, 0xc6, 0x83, 0x71, 0x36, 0x1b, 0xe6, 0x57, 0xd0, 0x4b, 0x70, 0x86, 0xc5,
	0xae, 0x4d, 0xf6, 0x3d, 0xf2, 0x1f, 0x9c, 0x57, 0x55, 0x22, 0x98, 0xb8, 0xba, 0xaa, 0xe9, 0xa3,
	0xbf, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0x48, 0x1b, 0x01, 0x7f, 0x76, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PrivateServiceClient is the client API for PrivateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrivateServiceClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Pong, error)
	JoinCluster(ctx context.Context, in *RaftNode, opts ...grpc.CallOption) (*empty.Empty, error)
	GetAuth(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AuthConfig, error)
	SetAuth(ctx context.Context, in *AuthConfig, opts ...grpc.CallOption) (*AuthConfig, error)
}

type privateServiceClient struct {
	cc *grpc.ClientConn
}

func NewPrivateServiceClient(cc *grpc.ClientConn) PrivateServiceClient {
	return &privateServiceClient{cc}
}

func (c *privateServiceClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/api.PrivateService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateServiceClient) JoinCluster(ctx context.Context, in *RaftNode, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.PrivateService/JoinCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateServiceClient) GetAuth(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AuthConfig, error) {
	out := new(AuthConfig)
	err := c.cc.Invoke(ctx, "/api.PrivateService/GetAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateServiceClient) SetAuth(ctx context.Context, in *AuthConfig, opts ...grpc.CallOption) (*AuthConfig, error) {
	out := new(AuthConfig)
	err := c.cc.Invoke(ctx, "/api.PrivateService/SetAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivateServiceServer is the server API for PrivateService service.
type PrivateServiceServer interface {
	Ping(context.Context, *empty.Empty) (*Pong, error)
	JoinCluster(context.Context, *RaftNode) (*empty.Empty, error)
	GetAuth(context.Context, *empty.Empty) (*AuthConfig, error)
	SetAuth(context.Context, *AuthConfig) (*AuthConfig, error)
}

func RegisterPrivateServiceServer(s *grpc.Server, srv PrivateServiceServer) {
	s.RegisterService(&_PrivateService_serviceDesc, srv)
}

func _PrivateService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PrivateService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateServiceServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateService_JoinCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateServiceServer).JoinCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PrivateService/JoinCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateServiceServer).JoinCluster(ctx, req.(*RaftNode))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateService_GetAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateServiceServer).GetAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PrivateService/GetAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateServiceServer).GetAuth(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateService_SetAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateServiceServer).SetAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PrivateService/SetAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateServiceServer).SetAuth(ctx, req.(*AuthConfig))
	}
	return interceptor(ctx, in, info, handler)
}

var _PrivateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.PrivateService",
	HandlerType: (*PrivateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PrivateService_Ping_Handler,
		},
		{
			MethodName: "JoinCluster",
			Handler:    _PrivateService_JoinCluster_Handler,
		},
		{
			MethodName: "GetAuth",
			Handler:    _PrivateService_GetAuth_Handler,
		},
		{
			MethodName: "SetAuth",
			Handler:    _PrivateService_SetAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/graphik.proto",
}
