// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/graphik.proto

package apipb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/struct"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
	regexp "regexp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _regex_Path_Gtype = regexp.MustCompile(`^.{1,225}$`)

func (this *Path) Validate() error {
	if !_regex_Path_Gtype.MatchString(this.Gtype) {
		return github_com_mwitkow_go_proto_validators.FieldError("Gtype", fmt.Errorf(`value '%v' must be a string conforming to regex "^.{1,225}$"`, this.Gtype))
	}
	return nil
}
func (this *Metadata) Validate() error {
	return nil
}
func (this *Paths) Validate() error {
	for _, item := range this.Paths {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Paths", err)
			}
		}
	}
	return nil
}
func (this *Node) Validate() error {
	if this.Path != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Path); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Path", err)
		}
	}
	if this.Attributes != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Attributes); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Attributes", err)
		}
	}
	if this.Metadata != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Metadata); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Metadata", err)
		}
	}
	return nil
}
func (this *NodeConstructor) Validate() error {
	if nil == this.Path {
		return github_com_mwitkow_go_proto_validators.FieldError("Path", fmt.Errorf("message must exist"))
	}
	if this.Path != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Path); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Path", err)
		}
	}
	if this.Attributes != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Attributes); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Attributes", err)
		}
	}
	return nil
}
func (this *NodeConstructors) Validate() error {
	for _, item := range this.Nodes {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Nodes", err)
			}
		}
	}
	return nil
}
func (this *Nodes) Validate() error {
	for _, item := range this.Nodes {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Nodes", err)
			}
		}
	}
	return nil
}
func (this *NodeDetail) Validate() error {
	if this.Path != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Path); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Path", err)
		}
	}
	if this.Attributes != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Attributes); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Attributes", err)
		}
	}
	// Validation of proto3 map<> fields is unsupported.
	// Validation of proto3 map<> fields is unsupported.
	if this.Metadata != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Metadata); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Metadata", err)
		}
	}
	return nil
}
func (this *NodeDetails) Validate() error {
	for _, item := range this.NodeDetails {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("NodeDetails", err)
			}
		}
	}
	return nil
}
func (this *NodeDetailFilter) Validate() error {
	if this.Path != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Path); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Path", err)
		}
	}
	if this.EdgesFrom != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.EdgesFrom); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("EdgesFrom", err)
		}
	}
	if this.EdgesTo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.EdgesTo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("EdgesTo", err)
		}
	}
	return nil
}
func (this *Edge) Validate() error {
	if this.Path != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Path); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Path", err)
		}
	}
	if this.Attributes != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Attributes); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Attributes", err)
		}
	}
	if this.From != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.From); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("From", err)
		}
	}
	if this.To != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.To); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("To", err)
		}
	}
	if this.Metadata != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Metadata); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Metadata", err)
		}
	}
	return nil
}
func (this *EdgeConstructor) Validate() error {
	if nil == this.Path {
		return github_com_mwitkow_go_proto_validators.FieldError("Path", fmt.Errorf("message must exist"))
	}
	if this.Path != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Path); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Path", err)
		}
	}
	if this.Attributes != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Attributes); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Attributes", err)
		}
	}
	if nil == this.From {
		return github_com_mwitkow_go_proto_validators.FieldError("From", fmt.Errorf("message must exist"))
	}
	if this.From != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.From); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("From", err)
		}
	}
	if nil == this.To {
		return github_com_mwitkow_go_proto_validators.FieldError("To", fmt.Errorf("message must exist"))
	}
	if this.To != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.To); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("To", err)
		}
	}
	return nil
}
func (this *EdgeConstructors) Validate() error {
	for _, item := range this.Edges {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Edges", err)
			}
		}
	}
	return nil
}
func (this *Edges) Validate() error {
	for _, item := range this.Edges {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Edges", err)
			}
		}
	}
	return nil
}
func (this *EdgeDetail) Validate() error {
	if this.Path != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Path); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Path", err)
		}
	}
	if this.Attributes != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Attributes); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Attributes", err)
		}
	}
	if this.From != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.From); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("From", err)
		}
	}
	if this.To != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.To); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("To", err)
		}
	}
	if this.Metadata != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Metadata); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Metadata", err)
		}
	}
	return nil
}
func (this *EdgeDetails) Validate() error {
	for _, item := range this.Edges {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Edges", err)
			}
		}
	}
	return nil
}

var _regex_EdgeFilter_Gtype = regexp.MustCompile(`^.{1,225}$`)

func (this *EdgeFilter) Validate() error {
	if nil == this.NodePath {
		return github_com_mwitkow_go_proto_validators.FieldError("NodePath", fmt.Errorf("message must exist"))
	}
	if this.NodePath != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.NodePath); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("NodePath", err)
		}
	}
	if !_regex_EdgeFilter_Gtype.MatchString(this.Gtype) {
		return github_com_mwitkow_go_proto_validators.FieldError("Gtype", fmt.Errorf(`value '%v' must be a string conforming to regex "^.{1,225}$"`, this.Gtype))
	}
	if !(this.Limit > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Limit", fmt.Errorf(`value '%v' must be greater than '0'`, this.Limit))
	}
	return nil
}

var _regex_Filter_Gtype = regexp.MustCompile(`^.{1,225}$`)

func (this *Filter) Validate() error {
	if !_regex_Filter_Gtype.MatchString(this.Gtype) {
		return github_com_mwitkow_go_proto_validators.FieldError("Gtype", fmt.Errorf(`value '%v' must be a string conforming to regex "^.{1,225}$"`, this.Gtype))
	}
	if !(this.Limit > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Limit", fmt.Errorf(`value '%v' must be greater than '0'`, this.Limit))
	}
	return nil
}
func (this *MeFilter) Validate() error {
	if this.EdgesFrom != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.EdgesFrom); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("EdgesFrom", err)
		}
	}
	if this.EdgesTo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.EdgesTo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("EdgesTo", err)
		}
	}
	return nil
}

var _regex_ChannelFilter_Channel = regexp.MustCompile(`^.{1,225}$`)

func (this *ChannelFilter) Validate() error {
	if !_regex_ChannelFilter_Channel.MatchString(this.Channel) {
		return github_com_mwitkow_go_proto_validators.FieldError("Channel", fmt.Errorf(`value '%v' must be a string conforming to regex "^.{1,225}$"`, this.Channel))
	}
	return nil
}
func (this *SubGraphFilter) Validate() error {
	if nil == this.Nodes {
		return github_com_mwitkow_go_proto_validators.FieldError("Nodes", fmt.Errorf("message must exist"))
	}
	if this.Nodes != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Nodes); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Nodes", err)
		}
	}
	if nil == this.Edges {
		return github_com_mwitkow_go_proto_validators.FieldError("Edges", fmt.Errorf("message must exist"))
	}
	if this.Edges != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Edges); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Edges", err)
		}
	}
	return nil
}
func (this *StateChange) Validate() error {
	if this.Mutation != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Mutation); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Mutation", err)
		}
	}
	return nil
}
func (this *Mutation) Validate() error {
	if oneOfNester, ok := this.GetObject().(*Mutation_Node); ok {
		if oneOfNester.Node != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Node); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Node", err)
			}
		}
	}
	if oneOfNester, ok := this.GetObject().(*Mutation_Nodes); ok {
		if oneOfNester.Nodes != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Nodes); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Nodes", err)
			}
		}
	}
	if oneOfNester, ok := this.GetObject().(*Mutation_NodeConstructor); ok {
		if oneOfNester.NodeConstructor != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.NodeConstructor); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("NodeConstructor", err)
			}
		}
	}
	if oneOfNester, ok := this.GetObject().(*Mutation_NodeConstructors); ok {
		if oneOfNester.NodeConstructors != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.NodeConstructors); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("NodeConstructors", err)
			}
		}
	}
	if oneOfNester, ok := this.GetObject().(*Mutation_EdgeConstructor); ok {
		if oneOfNester.EdgeConstructor != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.EdgeConstructor); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("EdgeConstructor", err)
			}
		}
	}
	if oneOfNester, ok := this.GetObject().(*Mutation_EdgeConstructors); ok {
		if oneOfNester.EdgeConstructors != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.EdgeConstructors); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("EdgeConstructors", err)
			}
		}
	}
	if oneOfNester, ok := this.GetObject().(*Mutation_Edge); ok {
		if oneOfNester.Edge != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Edge); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Edge", err)
			}
		}
	}
	if oneOfNester, ok := this.GetObject().(*Mutation_Edges); ok {
		if oneOfNester.Edges != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Edges); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Edges", err)
			}
		}
	}
	if oneOfNester, ok := this.GetObject().(*Mutation_Path); ok {
		if oneOfNester.Path != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Path); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Path", err)
			}
		}
	}
	if oneOfNester, ok := this.GetObject().(*Mutation_Paths); ok {
		if oneOfNester.Paths != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Paths); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Paths", err)
			}
		}
	}
	if oneOfNester, ok := this.GetObject().(*Mutation_Patch); ok {
		if oneOfNester.Patch != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Patch); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Patch", err)
			}
		}
	}
	if oneOfNester, ok := this.GetObject().(*Mutation_Patches); ok {
		if oneOfNester.Patches != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Patches); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Patches", err)
			}
		}
	}
	if oneOfNester, ok := this.GetObject().(*Mutation_Empty); ok {
		if oneOfNester.Empty != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Empty); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Empty", err)
			}
		}
	}
	return nil
}
func (this *Graph) Validate() error {
	if this.Nodes != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Nodes); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Nodes", err)
		}
	}
	if this.Edges != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Edges); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Edges", err)
		}
	}
	return nil
}
func (this *Patch) Validate() error {
	if nil == this.Path {
		return github_com_mwitkow_go_proto_validators.FieldError("Path", fmt.Errorf("message must exist"))
	}
	if this.Path != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Path); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Path", err)
		}
	}
	if this.Attributes != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Attributes); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Attributes", err)
		}
	}
	return nil
}
func (this *Patches) Validate() error {
	for _, item := range this.Patches {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Patches", err)
			}
		}
	}
	return nil
}
func (this *Pong) Validate() error {
	return nil
}

var _regex_RaftNode_NodeId = regexp.MustCompile(`^.{1,225}$`)
var _regex_RaftNode_Address = regexp.MustCompile(`^.{1,225}$`)

func (this *RaftNode) Validate() error {
	if !_regex_RaftNode_NodeId.MatchString(this.NodeId) {
		return github_com_mwitkow_go_proto_validators.FieldError("NodeId", fmt.Errorf(`value '%v' must be a string conforming to regex "^.{1,225}$"`, this.NodeId))
	}
	if !_regex_RaftNode_Address.MatchString(this.Address) {
		return github_com_mwitkow_go_proto_validators.FieldError("Address", fmt.Errorf(`value '%v' must be a string conforming to regex "^.{1,225}$"`, this.Address))
	}
	return nil
}
func (this *RaftLog) Validate() error {
	return nil
}

var _regex_OutboundMessage_Channel = regexp.MustCompile(`^.{1,225}$`)

func (this *OutboundMessage) Validate() error {
	if !_regex_OutboundMessage_Channel.MatchString(this.Channel) {
		return github_com_mwitkow_go_proto_validators.FieldError("Channel", fmt.Errorf(`value '%v' must be a string conforming to regex "^.{1,225}$"`, this.Channel))
	}
	if nil == this.Data {
		return github_com_mwitkow_go_proto_validators.FieldError("Data", fmt.Errorf("message must exist"))
	}
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}

var _regex_Message_Channel = regexp.MustCompile(`^.{1,225}$`)

func (this *Message) Validate() error {
	if !_regex_Message_Channel.MatchString(this.Channel) {
		return github_com_mwitkow_go_proto_validators.FieldError("Channel", fmt.Errorf(`value '%v' must be a string conforming to regex "^.{1,225}$"`, this.Channel))
	}
	if nil == this.Data {
		return github_com_mwitkow_go_proto_validators.FieldError("Data", fmt.Errorf("message must exist"))
	}
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	if this.Sender != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Sender); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Sender", err)
		}
	}
	return nil
}

var _regex_Trigger_Method = regexp.MustCompile(`^.{1,225}$`)

func (this *Trigger) Validate() error {
	if !_regex_Trigger_Method.MatchString(this.Method) {
		return github_com_mwitkow_go_proto_validators.FieldError("Method", fmt.Errorf(`value '%v' must be a string conforming to regex "^.{1,225}$"`, this.Method))
	}
	if this.User != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("User", err)
		}
	}
	if this.State != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.State); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("State", err)
		}
	}
	return nil
}

var _regex_RequestIntercept_Method = regexp.MustCompile(`^.{1,225}$`)

func (this *RequestIntercept) Validate() error {
	if !_regex_RequestIntercept_Method.MatchString(this.Method) {
		return github_com_mwitkow_go_proto_validators.FieldError("Method", fmt.Errorf(`value '%v' must be a string conforming to regex "^.{1,225}$"`, this.Method))
	}
	if this.User != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("User", err)
		}
	}
	if oneOfNester, ok := this.GetRequest().(*RequestIntercept_Empty); ok {
		if oneOfNester.Empty != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Empty); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Empty", err)
			}
		}
	}
	if oneOfNester, ok := this.GetRequest().(*RequestIntercept_SubgraphFilter); ok {
		if oneOfNester.SubgraphFilter != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.SubgraphFilter); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("SubgraphFilter", err)
			}
		}
	}
	if oneOfNester, ok := this.GetRequest().(*RequestIntercept_Graph); ok {
		if oneOfNester.Graph != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Graph); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Graph", err)
			}
		}
	}
	if oneOfNester, ok := this.GetRequest().(*RequestIntercept_ChannelFilter); ok {
		if oneOfNester.ChannelFilter != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.ChannelFilter); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ChannelFilter", err)
			}
		}
	}
	if oneOfNester, ok := this.GetRequest().(*RequestIntercept_OutboundMessage); ok {
		if oneOfNester.OutboundMessage != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.OutboundMessage); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("OutboundMessage", err)
			}
		}
	}
	if oneOfNester, ok := this.GetRequest().(*RequestIntercept_EdgeFilter); ok {
		if oneOfNester.EdgeFilter != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.EdgeFilter); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("EdgeFilter", err)
			}
		}
	}
	if oneOfNester, ok := this.GetRequest().(*RequestIntercept_Paths); ok {
		if oneOfNester.Paths != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Paths); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Paths", err)
			}
		}
	}
	if oneOfNester, ok := this.GetRequest().(*RequestIntercept_Path); ok {
		if oneOfNester.Path != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Path); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Path", err)
			}
		}
	}
	if oneOfNester, ok := this.GetRequest().(*RequestIntercept_Patches); ok {
		if oneOfNester.Patches != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Patches); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Patches", err)
			}
		}
	}
	if oneOfNester, ok := this.GetRequest().(*RequestIntercept_Patch); ok {
		if oneOfNester.Patch != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Patch); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Patch", err)
			}
		}
	}
	if oneOfNester, ok := this.GetRequest().(*RequestIntercept_Filter); ok {
		if oneOfNester.Filter != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Filter); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Filter", err)
			}
		}
	}
	if oneOfNester, ok := this.GetRequest().(*RequestIntercept_NodeConstructors); ok {
		if oneOfNester.NodeConstructors != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.NodeConstructors); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("NodeConstructors", err)
			}
		}
	}
	if oneOfNester, ok := this.GetRequest().(*RequestIntercept_NodeConstructor); ok {
		if oneOfNester.NodeConstructor != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.NodeConstructor); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("NodeConstructor", err)
			}
		}
	}
	if oneOfNester, ok := this.GetRequest().(*RequestIntercept_MeFilter); ok {
		if oneOfNester.MeFilter != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.MeFilter); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("MeFilter", err)
			}
		}
	}
	if oneOfNester, ok := this.GetRequest().(*RequestIntercept_RaftNode); ok {
		if oneOfNester.RaftNode != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.RaftNode); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("RaftNode", err)
			}
		}
	}
	return nil
}
func (this *Decision) Validate() error {
	return nil
}
func (this *Schema) Validate() error {
	return nil
}
